definitions:
  handler.getActionsResponse:
    properties:
      actions:
        items:
          $ref: '#/definitions/models.Action'
        type: array
    type: object
  handler.predictActionRequest:
    description: Request containing the URL of the video to analyze
    properties:
      video_url:
        description: '@Description URL of the video to analyze'
        type: string
    required:
    - video_url
    type: object
  handler.pretictActionResponse:
    description: Response containing predicted actions in Uzbek language
    properties:
      predictions:
        description: '@Description List of predicted actions in Uzbek language'
        items:
          $ref: '#/definitions/models.Prediction'
        type: array
    type: object
  models.Action:
    properties:
      created_at:
        type: string
      id:
        type: integer
      predicted_actions:
        items:
          type: string
        type: array
      video_url:
        type: string
    type: object
  models.Prediction:
    properties:
      confidence:
        type: string
      label:
        type: string
    type: object
  response.BaseResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:4040
info:
  contact: {}
  description: API Server for Application
  title: ActionDetector API
  version: "1.0"
paths:
  /api/actions:
    delete:
      description: Delete all previously predicted actions
      produces:
      - application/json
      responses:
        "200":
          description: Successfully deleted all actions
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Delete all actions
      tags:
      - actions
    get:
      description: Get a list of all previously predicted actions
      produces:
      - application/json
      responses:
        "200":
          description: Returns the list of actions
          schema:
            $ref: '#/definitions/handler.getActionsResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Get all actions
      tags:
      - actions
  /api/files:
    post:
      consumes:
      - multipart/form-data
      description: Upload a video file with size limit of 50MB
      parameters:
      - description: Video file to upload (max 50MB)
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Returns the file link
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "400":
          description: Invalid file size or type
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Upload a video file
      tags:
      - video
  /api/predict:
    post:
      consumes:
      - application/json
      description: Upload a video URL and get predicted actions in Uzbek language
      parameters:
      - description: Request body with video URL
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.predictActionRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Returns predicted actions in Uzbek
          schema:
            $ref: '#/definitions/handler.pretictActionResponse'
        "400":
          description: Invalid request body
          schema:
            $ref: '#/definitions/response.BaseResponse'
        "500":
          description: Internal server error or prediction service error
          schema:
            $ref: '#/definitions/response.BaseResponse'
      summary: Predict actions from video
      tags:
      - prediction
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
