package models

import "time"

type Action struct {
	Id               int       `json:"id"`
	VideoURL         string    `json:"video_url"`
	PredictedActions []string  `json:"predicted_actions"`
	CreatedAt        time.Time `json:"created_at"`
}

var ActionMapping = map[string]string{
	// English to Uzbek mapping for Kinetics-400 action classes
	"abseiling":                           "arqon bilan tushish",
	"air drumming":                        "havoda baraban chalish",
	"answering questions":                 "savollarga javob berish",
	"applauding":                          "qarsak chalish",
	"applying cream":                      "krem surish",
	"archery":                             "kamon otish",
	"arm wrestling":                       "qo'l kurashi",
	"arranging flowers":                   "gullarni tartibga solish",
	"assembling computer":                 "kompyuterni yig'ish",
	"auctioning":                          "auksionda qatnashish",
	"baby waking up":                      "chaqaloqning uyg'onishi",
	"baking cookies":                      "pechene pishirish",
	"balloon blowing":                     "pufak shishirish",
	"bandaging":                           "bog'lash",
	"barbequing":                          "barbekyu qilish",
	"bartending":                          "barmenlik qilish",
	"beatboxing":                          "bitboks qilish",
	"bee keeping":                         "asalarichilik",
	"belly dancing":                       "qorin raqsi",
	"bench pressing":                      "shtanga ko'tarish",
	"bending back":                        "orqaga egilish",
	"bending metal":                       "metalni egish",
	"biking through snow":                 "qorda velosiped minish",
	"blasting sand":                       "qumni portlatish",
	"blowing glass":                       "shisha puflab shakl berish",
	"blowing nose":                        "burunni qoqish",
	"blowing out candles":                 "shamlarni o'chirish",
	"bobsledding":                         "bobsleyda uchish",
	"bookbinding":                         "kitob muqovalash",
	"bouncing on trampoline":              "batutda sakrash",
	"bowling":                             "bouling o'ynash",
	"braiding hair":                       "soch o'rish",
	"breading or flouring":                "non yoki un sepish",
	"breakdancing":                        "breyk-dans tushish",
	"brush painting":                      "cho'tka bilan bo'yash",
	"brushing hair":                       "soch tarash",
	"brushing teeth":                      "tish yuvish",
	"building cabinet":                    "shkaf yasash",
	"building shed":                       "omborxona qurish",
	"bungee jumping":                      "arqon bilan sakrash",
	"busking":                             "ko'chada qo'shiq aytish",
	"canoeing or kayaking":                "qayiqda suzish",
	"capoeira":                            "kapoeyra",
	"carrying baby":                       "chaqaloqni ko'tarib yurish",
	"cartwheeling":                        "g'ildirakcha oshish",
	"carving pumpkin":                     "qovoqni o'yib bezash",
	"catching fish":                       "baliq tutish",
	"catching or throwing baseball":       "beysbol tutish yoki otish",
	"catching or throwing frisbee":        "frisbi tutish yoki otish",
	"catching or throwing softball":       "softbol tutish yoki otish",
	"celebrating":                         "nishonlash",
	"changing oil":                        "moyni almashtirish",
	"changing wheel":                      "g'ildirakni almashtirish",
	"checking tires":                      "shinalarni tekshirish",
	"cheerleading":                        "cheerleading",
	"chopping wood":                       "o'tin yorish",
	"clapping":                            "qarsak chalish",
	"clay pottery making":                 "loydan idish yasash",
	"clean and jerk":                      "shtangani ko'tarish",
	"cleaning floor":                      "polni tozalash",
	"cleaning gutters":                    "novlarni tozalash",
	"cleaning pool":                       "basseynni tozalash",
	"cleaning shoes":                      "poyabzalni tozalash",
	"cleaning toilet":                     "hojatxonani tozalash",
	"cleaning windows":                    "derazalarni tozalash",
	"climbing a rope":                     "arqonga tirmashib chiqish",
	"climbing ladder":                     "narvonga chiqish",
	"climbing tree":                       "daraxtga chiqish",
	"contact juggling":                    "kontakt jonglyorlik",
	"cooking chicken":                     "tovuq pishirish",
	"cooking egg":                         "tuxum pishirish",
	"cooking on campfire":                 "gulxanda ovqat pishirish",
	"cooking sausages":                    "sosiska pishirish",
	"counting money":                      "pul sanash",
	"country line dancing":                "qishloq chiziq raqsi",
	"cracking neck":                       "bo'yinni qisirlatish",
	"crawling baby":                       "emaklab yurgan chaqaloq",
	"crossing river":                      "daryodan o'tish",
	"crying":                              "yig'lash",
	"curling hair":                        "sochni jingalak qilish",
	"cutting nails":                       "tirnoq olish",
	"cutting pineapple":                   "ananas kesish",
	"cutting watermelon":                  "tarvuz kesish",
	"dancing ballet":                      "balet raqsi",
	"dancing charleston":                  "charleston raqsi",
	"dancing gangnam style":               "gangnam style raqsi",
	"dancing macarena":                    "makarena raqsi",
	"deadlifting":                         "shtanga ko'tarish",
	"decorating the christmas tree":       "yangi yil archa bezash",
	"digging":                             "qazish",
	"dining":                              "ovqatlanish",
	"disc golfing":                        "disk golf o'ynash",
	"diving cliff":                        "qoyadan sho'ng'ish",
	"dodgeball":                           "dodgbol o'ynash",
	"doing aerobics":                      "aerobika bilan shug'ullanish",
	"doing laundry":                       "kir yuvish",
	"doing nails":                         "tirnoq pardozlash",
	"drawing":                             "chizish",
	"dribbling basketball":                "basketbol to'pini olib yurish",
	"drinking":                            "ichish",
	"drinking beer":                       "pivo ichish",
	"drinking shots":                      "spirtli ichimlik ichish",
	"driving car":                         "mashina haydash",
	"driving tractor":                     "traktor haydash",
	"drop kicking":                        "tepib tushirish",
	"drumming fingers":                    "barmoqlar bilan baraban chalish",
	"dunking basketball":                  "basketbol to'pini savatga tashlash",
	"dying hair":                          "soch bo'yash",
	"eating burger":                       "burger yeyish",
	"eating cake":                         "tort yeyish",
	"eating carrots":                      "sabzi yeyish",
	"eating chips":                        "chips yeyish",
	"eating doughnuts":                    "ponchik yeyish",
	"eating hotdog":                       "hotdog yeyish",
	"eating ice cream":                    "muzqaymoq yeyish",
	"eating spaghetti":                    "spagetti yeyish",
	"eating watermelon":                   "tarvuz yeyish",
	"egg hunting":                         "tuxum qidirish",
	"exercising arm":                      "qo'l mashqlari",
	"exercising with an exercise ball":    "mashq to'pi bilan mashq qilish",
	"extinguishing fire":                  "olovni o'chirish",
	"faceplanting":                        "yuztuban yiqilish",
	"feeding birds":                       "qushlarni oziqlantirish",
	"feeding fish":                        "baliqlarni oziqlantirish",
	"feeding goats":                       "echkilarni oziqlantirish",
	"filling eyebrows":                    "qoshlarni to'ldirish",
	"finger snapping":                     "barmoq qisirlatish",
	"fixing hair":                         "sochni tuzatish",
	"flipping pancake":                    "blinchikni ag'darish",
	"flying kite":                         "varrak uchirish",
	"folding clothes":                     "kiyimlarni taxlash",
	"folding napkins":                     "sochiqlarni taxlash",
	"folding paper":                       "qog'ozni taxlash",
	"front raises":                        "qo'llarni oldinga ko'tarish",
	"frying vegetables":                   "sabzavotlarni qovurish",
	"garbage collecting":                  "axlat yig'ish",
	"gargling":                            "og'izni chayish",
	"getting a haircut":                   "soch oldirish",
	"getting a tattoo":                    "tatu qildirish",
	"giving or receiving award":           "mukofot berish yoki olish",
	"golf chipping":                       "golf to'pini qisqa masofaga urish",
	"golf driving":                        "golf to'pini uzoqqa urish",
	"golf putting":                        "golf to'pini teshikka kiritish",
	"grinding meat":                       "go'shtni maydalash",
	"grooming dog":                        "itni parvarish qilish",
	"grooming horse":                      "otni parvarish qilish",
	"gymnastics tumbling":                 "gimnastika mashqlari",
	"hammer throw":                        "bolg'a uloqtirish",
	"headbanging":                         "boshni silkitish",
	"headbutting":                         "bosh bilan urish",
	"high jump":                           "balandlikka sakrash",
	"high kick":                           "yuqoriga tepish",
	"hitting baseball":                    "beysbol to'pini urish",
	"hockey stop":                         "xokkey to'xtashi",
	"holding snake":                       "ilonni ushlab turish",
	"hopscotch":                           "klassiki o'ynash",
	"hoverboarding":                       "hoverboardda yurish",
	"hugging":                             "quchoqlash",
	"hula hooping":                        "hula-hup aylantrish",
	"hurdling":                            "g'ovlardan sakrab o'tish",
	"hurling (sport)":                     "hurling (sport)",
	"ice climbing":                        "muzga tirmashib chiqish",
	"ice fishing":                         "muzda baliq tutish",
	"ice skating":                         "muzda uchish",
	"ironing":                             "dazmollash",
	"javelin throw":                       "nayza uloqtirish",
	"jetskiing":                           "suv motosiklida uchish",
	"jogging":                             "sekin yugurish",
	"juggling balls":                      "to'plarni jonglyor qilish",
	"juggling fire":                       "olovni jonglyor qilish",
	"juggling soccer ball":                "futbol to'pini jonglyor qilish",
	"jumping into pool":                   "basseinga sakrash",
	"jumpstyle dancing":                   "jumpstyle raqsi",
	"kicking field goal":                  "darvozaga tepish",
	"kicking soccer ball":                 "futbol to'pini tepish",
	"kissing":                             "o'pish",
	"kitesurfing":                         "kiteserfingi",
	"knitting":                            "to'qish",
	"krumping":                            "krumping raqsi",
	"laughing":                            "kulish",
	"laying bricks":                       "g'isht terish",
	"long jump":                           "uzunlikka sakrash",
	"lunge":                               "oldinga tashlanish",
	"making a cake":                       "tort tayyorlash",
	"making a sandwich":                   "sendvich tayyorlash",
	"making bed":                          "to'shakni tartibga keltirish",
	"making jewelry":                      "zargarlik buyumlari yasash",
	"making pizza":                        "pitsa tayyorlash",
	"making snowman":                      "qorbobo yasash",
	"making sushi":                        "sushi tayyorlash",
	"making tea":                          "choy damlash",
	"marching":                            "marsh qadami bilan yurish",
	"massaging back":                      "orqani uqalash",
	"massaging feet":                      "oyoqlarni uqalash",
	"massaging legs":                      "oyoqlarni uqalash",
	"massaging person's head":             "odamning boshini uqalash",
	"milking cow":                         "sigir sog'ish",
	"mopping floor":                       "polni artish",
	"motorcycling":                        "mototsiklda yurish",
	"moving furniture":                    "mebelni ko'chirish",
	"mowing lawn":                         "o't o'rish",
	"news anchoring":                      "yangiliklar boshlovchisi",
	"opening bottle":                      "shishani ochish",
	"opening present":                     "sovg'ani ochish",
	"paragliding":                         "paraglaydingda uchish",
	"parasailing":                         "parasaylingda uchish",
	"parkour":                             "parkur",
	"passing American football (in game)": "amerikan futbolini uzatish (o'yinda)",
	"passing American football (not in game)": "amerikan futbolini uzatish (o'yindan tashqari)",
	"peeling apples":                       "olmani archish",
	"peeling potatoes":                     "kartoshkani archish",
	"petting animal (not cat)":             "hayvonni silash (mushukdan tashqari)",
	"petting cat":                          "mushukni silash",
	"picking fruit":                        "meva terish",
	"planting trees":                       "daraxt ekish",
	"plastering":                           "suvoq qilish",
	"playing accordion":                    "akkordeon chalish",
	"playing badminton":                    "badminton o'ynash",
	"playing bagpipes":                     "volinka chalish",
	"playing basketball":                   "basketbol o'ynash",
	"playing bass guitar":                  "bas gitara chalish",
	"playing cards":                        "qarta o'ynash",
	"playing cello":                        "violonchel chalish",
	"playing chess":                        "shaxmat o'ynash",
	"playing clarinet":                     "klarnet chalish",
	"playing controller":                   "o'yin pulti bilan o'ynash",
	"playing cricket":                      "kriket o'ynash",
	"playing cymbals":                      "tarelkalar chalish",
	"playing didgeridoo":                   "didjeridu chalish",
	"playing drums":                        "baraban chalish",
	"playing flute":                        "fleyta chalish",
	"playing guitar":                       "gitara chalish",
	"playing harmonica":                    "garmonika chalish",
	"playing harp":                         "arfa chalish",
	"playing ice hockey":                   "muz xokkeyi o'ynash",
	"playing keyboard":                     "klaviatura chalish",
	"playing kickball":                     "kikbol o'ynash",
	"playing monopoly":                     "monopoliya o'ynash",
	"playing organ":                        "organ chalish",
	"playing paintball":                    "peyntbol o'ynash",
	"playing piano":                        "pianino chalish",
	"playing poker":                        "poker o'ynash",
	"playing recorder":                     "blokfleyta chalish",
	"playing saxophone":                    "saksofon chalish",
	"playing squash or racquetball":        "skvosh yoki raketbol o'ynash",
	"playing tennis":                       "tennis o'ynash",
	"playing trombone":                     "trombon chalish",
	"playing trumpet":                      "truba chalish",
	"playing ukulele":                      "ukulele chalish",
	"playing violin":                       "skripka chalish",
	"playing volleyball":                   "voleybol o'ynash",
	"playing xylophone":                    "ksilofon chalish",
	"pole vault":                           "langarcho'p bilan sakrash",
	"presenting weather forecast":          "ob-havo ma'lumotini taqdim etish",
	"pull ups":                             "turnikda tortilish",
	"pumping fist":                         "musht bilan ishora qilish",
	"pumping gas":                          "benzin quyish",
	"punching bag":                         "boks qopini urish",
	"punching person (boxing)":             "odamni mushtlash (boks)",
	"push up":                              "polda qo'l bilan tayanib ko'tarilish",
	"pushing car":                          "mashinani itarish",
	"pushing cart":                         "aravani itarish",
	"pushing wheelchair":                   "nogironlar aravachasini itarish",
	"reading book":                         "kitob o'qish",
	"reading newspaper":                    "gazeta o'qish",
	"recording music":                      "musiqa yozib olish",
	"riding a bike":                        "velosiped minish",
	"riding camel":                         "tuya minish",
	"riding elephant":                      "fil minish",
	"riding mechanical bull":               "mexanik buqani minish",
	"riding mountain bike":                 "tog' velosipedini minish",
	"riding mule":                          "xachir minish",
	"riding or walking with horse":         "ot minish yoki ot bilan yurish",
	"riding scooter":                       "skuter minish",
	"riding unicycle":                      "bir g'ildirakli velosiped minish",
	"ripping paper":                        "qog'ozni yirtish",
	"robot dancing":                        "robot raqsi",
	"rock climbing":                        "qoyaga tirmashib chiqish",
	"rock scissors paper":                  "tosh, qaychi, qog'oz o'yini",
	"roller skating":                       "rolikda uchish",
	"running on treadmill":                 "yugurish yo'lakchasida yugurish",
	"sailing":                              "yelkanli qayiqda suzish",
	"salsa dancing":                        "salsa raqsi",
	"sanding floor":                        "polni jilvirlash",
	"scrambling eggs":                      "tuxumni ko'pirtirib pishirish",
	"scuba diving":                         "akvalangda sho'ng'ish",
	"setting table":                        "dasturxon tuzash",
	"shaking hands":                        "qo'l siqishish",
	"shaking head":                         "boshni chayqash",
	"sharpening knives":                    "pichoqlarni charxlash",
	"sharpening pencil":                    "qalam ochish",
	"shaving head":                         "boshni qirish",
	"shaving legs":                         "oyoqlarni qirish",
	"shearing sheep":                       "qo'ylarni qirqish",
	"shining shoes":                        "poyabzalni yaltirash",
	"shooting basketball":                  "basketbol to'pini savatga tashlash",
	"shooting goal (soccer)":               "gol urish (futbol)",
	"shot put":                             "yadro itqitish",
	"shoveling snow":                       "qorni kurash",
	"shredding paper":                      "qog'ozni maydalash",
	"shuffling cards":                      "kartalarni aralashtirish",
	"side kick":                            "yon tepish",
	"sign language interpreting":           "imo-ishora tilini tarjima qilish",
	"singing":                              "qo'shiq aytish",
	"situp":                                "o'tirib-turish mashqi",
	"skateboarding":                        "skeytbordda uchish",
	"ski jumping":                          "chang'ida sakrash",
	"skiing (not slalom or crosscountry)":  "chang'i uchish (slalom yoki kross-kantri emas)",
	"skiing crosscountry":                  "kross-kantri chang'i uchish",
	"skiing slalom":                        "slalom chang'i uchish",
	"skipping rope":                        "arqon sakrash",
	"skydiving":                            "parashyutda sakrash",
	"slacklining":                          "tarang arqonda muvozanat saqlash",
	"slapping":                             "shapaloq urish",
	"sled dog racing":                      "chana itlari poygasi",
	"smoking":                              "chekish",
	"smoking hookah":                       "kalyon chekish",
	"snatch weight lifting":                "shtangani ko'tarish",
	"sneezing":                             "aksirish",
	"sniffing":                             "hidlash",
	"snorkeling":                           "snorkelingda suzish",
	"snowboarding":                         "snoubordda uchish",
	"snowkiting":                           "qorda kayt bilan uchish",
	"snowmobiling":                         "qor motosiklida yurish",
	"somersaulting":                        "umbaloq oshish",
	"spinning poi":                         "poi aylantirish",
	"spray painting":                       "purkab bo'yash",
	"spraying":                             "purkash",
	"springboard diving":                   "tramplindan sho'ng'ish",
	"squat":                                "o'tirib-turish",
	"sticking tongue out":                  "tilni chiqarish",
	"stomping grapes":                      "uzumni ezish",
	"stretching arm":                       "qo'lni cho'zish",
	"stretching leg":                       "oyoqni cho'zish",
	"strumming guitar":                     "gitara chalish",
	"surfing crowd":                        "olomonda serfingi",
	"surfing water":                        "suvda serfingi",
	"sweeping floor":                       "polni supurish",
	"swimming backstroke":                  "chalqancha suzish",
	"swimming breast stroke":               "brass usulida suzish",
	"swimming butterfly stroke":            "kapalak usulida suzish",
	"swing dancing":                        "sving raqsi",
	"swinging legs":                        "oyoqlarni silkitish",
	"swinging on something":                "biror narsada tebranish",
	"sword fighting":                       "qilich jangi",
	"tai chi":                              "tai chi",
	"taking a shower":                      "dush qabul qilish",
	"tango dancing":                        "tango raqsi",
	"tap dancing":                          "tep-dansi",
	"tapping guitar":                       "gitarani taqillatish",
	"tapping pen":                          "ruchkani taqillatish",
	"tasting beer":                         "pivo tatib ko'rish",
	"tasting food":                         "ovqatni tatib ko'rish",
	"testifying":                           "guvohlik berish",
	"texting":                              "xabar yozish",
	"throwing axe":                         "bolta otish",
	"throwing ball":                        "to'p otish",
	"throwing discus":                      "disk otish",
	"tickling":                             "qitiqlatish",
	"tobogganing":                          "toboganda uchish",
	"tossing coin":                         "tanga tashlash",
	"tossing salad":                        "salat aralashtirish",
	"training dog":                         "itni o'rgatish",
	"trapezing":                            "trapetsiyada mashq qilish",
	"trimming or shaving beard":            "soqolni qisqartirish yoki qirish",
	"trimming trees":                       "daraxtlarni kesish",
	"triple jump":                          "uch hatlab sakrash",
	"tying bow tie":                        "galstuk-babochka bog'lash",
	"tying knot (not on a tie)":            "tugun bog'lash (galstukda emas)",
	"tying tie":                            "galstuk bog'lash",
	"unboxing":                             "qutidan chiqarish",
	"unloading truck":                      "yuk mashinasini bo'shatish",
	"using computer":                       "kompyuterdan foydalanish",
	"using remote controller (not gaming)": "masofadan boshqarish pultidan foydalanish (o'yin emas)",
	"using segway":                         "segveydan foydalanish",
	"vault":                                "gimnastik sakrash",
	"waiting in line":                      "navbatda turish",
	"walking the dog":                      "it sayr qildirish",
	"washing dishes":                       "idish yuvish",
	"washing feet":                         "oyoqlarni yuvish",
	"washing hair":                         "soch yuvish",
	"washing hands":                        "qo'l yuvish",
	"water skiing":                         "suvda chang'i uchish",
	"water sliding":                        "suv sirpanchig'ida uchish",
	"watering plants":                      "o'simliklarga suv quyish",
	"waxing back":                          "orqani mumlab epilyatsiya qilish",
	"waxing chest":                         "ko'krakni mumlab epilyatsiya qilish",
	"waxing eyebrows":                      "qoshlarni mumlab epilyatsiya qilish",
	"waxing legs":                          "oyoqlarni mumlab epilyatsiya qilish",
	"weaving basket":                       "savat to'qish",
	"welding":                              "payvandlash",
	"whistling":                            "hushtak chalish",
	"windsurfing":                          "vindserfingda uchish",
	"wrapping present":                     "sovg'ani o'rash",
	"wrestling":                            "kurash",
	"writing":                              "yozish",
	"yawning":                              "esnash",
	"yoga":                                 "yoga",
	"zumba":                                "zumba",
}
